name: PHP Code Quality Check

on:
  push:
    branches:
      - main

jobs:
  php:
    name: PHP 8.1, and 8.2
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version: [8.1, 8.2]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: curl

      - name: Install dependencies
        run: composer install

      - name: Run PHPStan
        run: vendor/bin/phpstan analyse

      - name: Run PHP CS Fixer
        run: vendor/bin/php-cs-fixer fix --dry-run --stop-on-violation

      - name: Run PHPUnit tests
        run: vendor/bin/phpunit
